//* ALERT ACTIONS
const DISPLAY_ALERT = "SHOW_ALERT";
const CLEAR_ALERT = "CLEAR_ALERT";

//* REGISTER LOGIN USER ACTIONS
const SETUP_USER_BEGIN = "SETUP_USER_BEGIN";
const SETUP_USER_SUCCESS = "SETUP_USER_SUCCESS";
const SETUP_USER_ERROR = "SETUP_USER_ERROR";

//* TOGGLE BIG & SMALL SIDEBAR ACTIONS
const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";
const LOGOUT_USER = "LOGOUT_USER";

//* UPDATE USER ACTIONS
const UPDATE_USER_BEGIN = "UPDATE_USER_BEGIN";
const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
const UPDATE_USER_ERROR = "UPDATE_USER_ERROR";

//* HANDLE CHANGE IN FORM
const HANDLE_CHANGE = "HANDLE_CHANGE";

//* CLEAR FORM VALUES
const CLEAR_VALUES = "CLEAR_VALUES";

//* CREATE NEW JOB
const CREATE_JOB_BEGIN = "CREATE_JOB_BEGIN";
const CREATE_JOB_SUCCESS = "CREATE_JOB_SUCCESS";
const CREATE_JOB_ERROR = "CREATE_JOB_ERROR";

//* GET ALL JOBS
const GET_JOBS_BEGIN = "GET_JOBS_BEGIN";
const GET_JOBS_SUCCESS = "GET_JOBS_SUCCESS";

//* EDIT JOB
const SET_EDIT_JOB = "SET_EDIT_JOB";
const EDIT_JOB_BEGIN = "EDIT_JOB_BEGIN";
const EDIT_JOB_SUCCESS = "EDIT_JOB_SUCCESS";
const EDIT_JOB_ERROR = "EDIT_JOB_ERROR";

//* DELETE JOB
const DELETE_JOB_BEGIN = "DELETE_JOB_BEGIN";

//* SHOW STATS
const SHOW_STATS_BEGIN = "SHOW_STATS_BEGIN";
const SHOW_STATS_SUCCESS = "SHOW_STATS_SUCCESS";

//* CLEAR FILTERS
const CLEAR_FILTERS = "CLEAR_FILTERS";

//* PAGINATION
const CHANGE_PAGE = "CHANGE_PAGE";

export {
  DISPLAY_ALERT,
  CLEAR_ALERT,
  SETUP_USER_BEGIN,
  SETUP_USER_SUCCESS,
  SETUP_USER_ERROR,
  TOGGLE_SIDEBAR,
  LOGOUT_USER,
  UPDATE_USER_BEGIN,
  UPDATE_USER_SUCCESS,
  UPDATE_USER_ERROR,
  HANDLE_CHANGE,
  CLEAR_VALUES,
  CREATE_JOB_BEGIN,
  CREATE_JOB_SUCCESS,
  CREATE_JOB_ERROR,
  GET_JOBS_BEGIN,
  GET_JOBS_SUCCESS,
  SET_EDIT_JOB,
  DELETE_JOB_BEGIN,
  EDIT_JOB_SUCCESS,
  EDIT_JOB_BEGIN,
  EDIT_JOB_ERROR,
  SHOW_STATS_BEGIN,
  SHOW_STATS_SUCCESS,
  CLEAR_FILTERS,
  CHANGE_PAGE,
};
